---

- name: Prep
  ansible.builtin.include_tasks: prep.yaml

# A kubernetes (or OpenShift) host and an API key must be set.
# We will either have authenticated against an OpenShift server
# or the AWX kubernetes credentials will have injected suitable
# values for the K8S_AUTH_HOST and K8S_AUTH_API_KEY environment variables.
# Either way the ansible variables 'k8s_auth_host' and
# 'k8s_auth_api_key' will have been set.
- name: Assert authentication (host/api)
  ansible.builtin.assert:
    that:
    - k8s_auth_host|length > 0
    - k8s_auth_api_key|length > 0
  when: k8s_kubeconfig|length == 0

- name: Assert authentication (kubeconfig)
  ansible.builtin.assert:
    that:
    - k8s_auth_host|length > 0
    - k8s_kubeconfig|length > 0
  when: k8s_auth_api_key|length == 0

# Go...

- name: Deploy/Undeploy
  module_defaults:
    group/k8s:
      host: "{{ k8s_auth_host }}"
      api_key: "{{ k8s_auth_api_key }}"
      kubeconfig: "{{ k8s_kubeconfig }}"
  block:

  - name: Deploy
    ansible.builtin.include_tasks: deploy.yaml
    when: d_state|string == 'present'
  - name: Undeploy
    ansible.builtin.include_tasks: undeploy.yaml
    when: d_state|string == 'absent'
